server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Fallback SPA
  location / {
    try_files $uri /index.html;
  }

  # Cache per asset fingerprintati
  location ~* \.(js|css|woff2?|png|jpg|jpeg|gif|svg)$ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}
